"""raw rows may exist before a job or county

Revision ID: 1c15277b8000
Revises: b4dcfa4ed5eb
Create Date: 2026-08-02 22:06:08.503235

"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "1c15277b8000"
down_revision: str | None = "b4dcfa4ed5eb"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("raw_surplus_rows", "ingestion_job_id", existing_type=sa.UUID(), nullable=True)
    op.alter_column("raw_surplus_rows", "county_id", existing_type=sa.UUID(), nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("raw_surplus_rows", "county_id", existing_type=sa.UUID(), nullable=False)
    op.alter_column("raw_surplus_rows", "ingestion_job_id", existing_type=sa.UUID(), nullable=False)
    # ### end Alembic commands ###
