"""phase 2a extraction schema

Revision ID: 1f57c8db7223
Revises: 9f2ecd86a736
Create Date: 2026-08-02 18:46:22.349901

"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = "1f57c8db7223"
down_revision: str | None = "9f2ecd86a736"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None

# Autogenerate never emits DROP TYPE; see 9f2ecd86a736 for the same handling.
_ENUM_TYPE_NAMES: tuple[str, ...] = ("pdf_type",)

_RAW_ROWS_DOC_FK = "fk_raw_surplus_rows_parsed_document_id"


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "parsed_documents",
        sa.Column("county_id", sa.Uuid(), nullable=True),
        sa.Column("ingestion_job_id", sa.Uuid(), nullable=True),
        sa.Column("source_file_path", sa.String(length=1000), nullable=False),
        sa.Column("source_file_sha256", sa.String(length=64), nullable=False),
        sa.Column("page_count", sa.Integer(), nullable=False),
        sa.Column(
            "pdf_type",
            sa.Enum("searchable", "scanned", "hybrid", "empty", name="pdf_type"),
            nullable=False,
        ),
        sa.Column("ocr_required", sa.Boolean(), nullable=False),
        sa.Column("winning_strategy", sa.String(length=100), nullable=True),
        sa.Column("table_count", sa.Integer(), nullable=False),
        sa.Column("row_count", sa.Integer(), nullable=False),
        sa.Column("classification_confidence", sa.Float(), nullable=True),
        sa.Column("extraction_confidence", sa.Float(), nullable=True),
        sa.Column("page_profiles", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("strategy_scores", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("warnings", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("error_message", sa.Text(), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["county_id"], ["counties.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["ingestion_job_id"], ["ingestion_jobs.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_parsed_documents_county_id"), "parsed_documents", ["county_id"], unique=False
    )
    op.create_index(
        op.f("ix_parsed_documents_ingestion_job_id"),
        "parsed_documents",
        ["ingestion_job_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_parsed_documents_source_file_sha256"),
        "parsed_documents",
        ["source_file_sha256"],
        unique=False,
    )
    op.add_column("raw_surplus_rows", sa.Column("parsed_document_id", sa.Uuid(), nullable=True))
    op.add_column(
        "raw_surplus_rows",
        sa.Column("original_headers", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    )
    op.add_column(
        "raw_surplus_rows", sa.Column("source_pdf_sha256", sa.String(length=64), nullable=True)
    )
    op.add_column("raw_surplus_rows", sa.Column("table_index", sa.Integer(), nullable=True))
    op.add_column("raw_surplus_rows", sa.Column("row_index_on_page", sa.Integer(), nullable=True))
    op.add_column(
        "raw_surplus_rows", sa.Column("extraction_strategy", sa.String(length=100), nullable=True)
    )
    op.add_column("raw_surplus_rows", sa.Column("extraction_confidence", sa.Float(), nullable=True))
    op.create_index(
        op.f("ix_raw_surplus_rows_parsed_document_id"),
        "raw_surplus_rows",
        ["parsed_document_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_raw_surplus_rows_source_pdf_sha256"),
        "raw_surplus_rows",
        ["source_pdf_sha256"],
        unique=False,
    )
    op.create_foreign_key(
        _RAW_ROWS_DOC_FK,
        "raw_surplus_rows",
        "parsed_documents",
        ["parsed_document_id"],
        ["id"],
        ondelete="SET NULL",
    )
    op.alter_column(
        "surplus_cases",
        "surplus_amount",
        existing_type=sa.NUMERIC(precision=14, scale=2),
        nullable=True,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # Restoring NOT NULL fails loudly if any case has a NULL surplus_amount. That is
    # intended: those rows are cases where the county published no surplus, and silently
    # deleting or zero-filling them would destroy real data. Resolve them explicitly first.
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "surplus_cases",
        "surplus_amount",
        existing_type=sa.NUMERIC(precision=14, scale=2),
        nullable=False,
    )
    op.drop_constraint(_RAW_ROWS_DOC_FK, "raw_surplus_rows", type_="foreignkey")
    op.drop_index(op.f("ix_raw_surplus_rows_source_pdf_sha256"), table_name="raw_surplus_rows")
    op.drop_index(op.f("ix_raw_surplus_rows_parsed_document_id"), table_name="raw_surplus_rows")
    op.drop_column("raw_surplus_rows", "extraction_confidence")
    op.drop_column("raw_surplus_rows", "extraction_strategy")
    op.drop_column("raw_surplus_rows", "row_index_on_page")
    op.drop_column("raw_surplus_rows", "table_index")
    op.drop_column("raw_surplus_rows", "source_pdf_sha256")
    op.drop_column("raw_surplus_rows", "original_headers")
    op.drop_column("raw_surplus_rows", "parsed_document_id")
    op.drop_index(op.f("ix_parsed_documents_source_file_sha256"), table_name="parsed_documents")
    op.drop_index(op.f("ix_parsed_documents_ingestion_job_id"), table_name="parsed_documents")
    op.drop_index(op.f("ix_parsed_documents_county_id"), table_name="parsed_documents")
    op.drop_table("parsed_documents")
    # ### end Alembic commands ###
    bind = op.get_bind()
    for enum_name in _ENUM_TYPE_NAMES:
        sa.Enum(name=enum_name).drop(bind, checkfirst=True)
