"""phase 2c profile learning schema

Revision ID: 7115f38f3379
Revises: 859de4943a15
Create Date: 2026-08-02 20:30:00.067230

"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = "7115f38f3379"
down_revision: str | None = "859de4943a15"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # Autogenerate omits server defaults, which makes a NOT NULL column impossible to add
    # to a table that already holds rows. The defaults below let existing profiles adopt
    # sensible values -- observed once, unapproved, current -- instead of failing.
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "parsing_profile_versions",
        sa.Column("times_observed", sa.Integer(), nullable=False, server_default="1"),
    )
    op.add_column(
        "parsing_profile_versions",
        sa.Column("observed_file_hashes", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    )
    op.add_column(
        "parsing_profile_versions",
        sa.Column("is_approved", sa.Boolean(), nullable=False, server_default=sa.false()),
    )
    op.add_column(
        "parsing_profile_versions",
        sa.Column("superseded", sa.Boolean(), nullable=False, server_default=sa.false()),
    )
    op.create_index(
        op.f("ix_parsing_profile_versions_superseded"),
        "parsing_profile_versions",
        ["superseded"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("ix_parsing_profile_versions_superseded"), table_name="parsing_profile_versions"
    )
    op.drop_column("parsing_profile_versions", "superseded")
    op.drop_column("parsing_profile_versions", "is_approved")
    op.drop_column("parsing_profile_versions", "observed_file_hashes")
    op.drop_column("parsing_profile_versions", "times_observed")
    # ### end Alembic commands ###
