"""phase 2b interpretation schema

Revision ID: 859de4943a15
Revises: 1f57c8db7223
Create Date: 2026-08-02 19:39:43.062025

"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "859de4943a15"
down_revision: str | None = "1f57c8db7223"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None

# Autogenerate never emits DROP TYPE; see 9f2ecd86a736 for the same handling.
_ENUM_TYPE_NAMES: tuple[str, ...] = ("surplus_source_type", "mapping_method_type")


# add_column does not create a native enum type the way create_table does, so
# surplus_source_type has to be created explicitly first. mapping_method_type is created
# implicitly by the document_column_mappings table below and must not be created here.
_SURPLUS_SOURCE_ENUM = sa.Enum(
    "explicit",
    "county_config",
    "derived",
    "ambiguous",
    "absent",
    name="surplus_source_type",
)


def upgrade() -> None:
    _SURPLUS_SOURCE_ENUM.create(op.get_bind(), checkfirst=True)
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "document_column_mappings",
        sa.Column("parsed_document_id", sa.Uuid(), nullable=False),
        sa.Column("table_index", sa.Integer(), nullable=False),
        sa.Column("column_position", sa.Integer(), nullable=False),
        sa.Column("original_header", sa.String(length=300), nullable=False),
        sa.Column("canonical_field", sa.String(length=100), nullable=True),
        sa.Column(
            "method",
            sa.Enum(
                "county_override",
                "exact_alias",
                "fuzzy_alias",
                "value_inference",
                "surplus_explicit",
                "unresolved",
                name="mapping_method_type",
            ),
            nullable=False,
        ),
        sa.Column("confidence", sa.Float(), nullable=False),
        sa.Column("evidence", sa.Text(), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["parsed_document_id"], ["parsed_documents.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "parsed_document_id",
            "table_index",
            "column_position",
            name="uq_document_column_mappings_position",
        ),
    )
    op.create_index(
        op.f("ix_document_column_mappings_canonical_field"),
        "document_column_mappings",
        ["canonical_field"],
        unique=False,
    )
    op.create_index(
        op.f("ix_document_column_mappings_original_header"),
        "document_column_mappings",
        ["original_header"],
        unique=False,
    )
    op.create_index(
        op.f("ix_document_column_mappings_parsed_document_id"),
        "document_column_mappings",
        ["parsed_document_id"],
        unique=False,
    )
    op.add_column("surplus_cases", sa.Column("surplus_is_explicit", sa.Boolean(), nullable=False))
    op.add_column(
        "surplus_cases",
        sa.Column(
            "surplus_source",
            sa.Enum(
                "explicit",
                "county_config",
                "derived",
                "ambiguous",
                "absent",
                name="surplus_source_type",
            ),
            nullable=False,
        ),
    )
    op.add_column(
        "surplus_cases", sa.Column("surplus_source_column", sa.String(length=300), nullable=True)
    )
    op.add_column(
        "surplus_cases",
        sa.Column("sale_amount_published", sa.Numeric(precision=14, scale=2), nullable=True),
    )
    op.add_column(
        "surplus_cases", sa.Column("winning_bid", sa.Numeric(precision=14, scale=2), nullable=True)
    )
    op.add_column(
        "surplus_cases", sa.Column("opening_bid", sa.Numeric(precision=14, scale=2), nullable=True)
    )
    op.add_column(
        "surplus_cases",
        sa.Column("assessed_value", sa.Numeric(precision=14, scale=2), nullable=True),
    )
    op.add_column(
        "surplus_cases",
        sa.Column("appraised_value", sa.Numeric(precision=14, scale=2), nullable=True),
    )
    op.add_column(
        "surplus_cases", sa.Column("taxes_due", sa.Numeric(precision=14, scale=2), nullable=True)
    )
    op.add_column(
        "surplus_cases", sa.Column("fees_amount", sa.Numeric(precision=14, scale=2), nullable=True)
    )
    op.add_column(
        "surplus_cases",
        sa.Column("face_value_amount", sa.Numeric(precision=14, scale=2), nullable=True),
    )
    op.add_column(
        "surplus_cases",
        sa.Column("overbid_amount", sa.Numeric(precision=14, scale=2), nullable=True),
    )
    op.add_column(
        "surplus_cases",
        sa.Column("purchase_amount", sa.Numeric(precision=14, scale=2), nullable=True),
    )
    op.add_column(
        "surplus_cases",
        sa.Column("refunded_amount", sa.Numeric(precision=14, scale=2), nullable=True),
    )
    op.add_column(
        "surplus_cases",
        sa.Column("remaining_amount", sa.Numeric(precision=14, scale=2), nullable=True),
    )
    op.create_index(
        op.f("ix_surplus_cases_surplus_source"), "surplus_cases", ["surplus_source"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_surplus_cases_surplus_source"), table_name="surplus_cases")
    op.drop_column("surplus_cases", "remaining_amount")
    op.drop_column("surplus_cases", "refunded_amount")
    op.drop_column("surplus_cases", "purchase_amount")
    op.drop_column("surplus_cases", "overbid_amount")
    op.drop_column("surplus_cases", "face_value_amount")
    op.drop_column("surplus_cases", "fees_amount")
    op.drop_column("surplus_cases", "taxes_due")
    op.drop_column("surplus_cases", "appraised_value")
    op.drop_column("surplus_cases", "assessed_value")
    op.drop_column("surplus_cases", "opening_bid")
    op.drop_column("surplus_cases", "winning_bid")
    op.drop_column("surplus_cases", "sale_amount_published")
    op.drop_column("surplus_cases", "surplus_source_column")
    op.drop_column("surplus_cases", "surplus_source")
    op.drop_column("surplus_cases", "surplus_is_explicit")
    op.drop_index(
        op.f("ix_document_column_mappings_parsed_document_id"),
        table_name="document_column_mappings",
    )
    op.drop_index(
        op.f("ix_document_column_mappings_original_header"), table_name="document_column_mappings"
    )
    op.drop_index(
        op.f("ix_document_column_mappings_canonical_field"), table_name="document_column_mappings"
    )
    op.drop_table("document_column_mappings")
    # ### end Alembic commands ###
    bind = op.get_bind()
    for enum_name in _ENUM_TYPE_NAMES:
        sa.Enum(name=enum_name).drop(bind, checkfirst=True)
