"""initial schema

Revision ID: 9f2ecd86a736
Revises: 
Create Date: 2026-08-02 17:43:52.272929

"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = "9f2ecd86a736"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None

# Autogenerate emits CREATE TYPE implicitly when creating tables, but never emits
# DROP TYPE on downgrade. Without this list a downgrade leaves the enums behind and
# the next upgrade fails with "type ... already exists".
_ENUM_TYPE_NAMES: tuple[str, ...] = (
    "classification_method",
    "contact_type",
    "county_source_type",
    "deal_stage",
    "export_status",
    "export_type",
    "extraction_method",
    "ingestion_job_status",
    "interaction_type",
    "lead_status",
    "owner_type",
    "publishing_frequency",
    "research_status",
    "surplus_case_status",
    "user_role",
)


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "airtable_sync_records",
        sa.Column("local_table", sa.String(length=100), nullable=False),
        sa.Column("local_id", sa.Uuid(), nullable=False),
        sa.Column("airtable_table_name", sa.String(length=100), nullable=False),
        sa.Column("airtable_record_id", sa.String(length=50), nullable=False),
        sa.Column("last_synced_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("sync_hash", sa.String(length=64), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "airtable_table_name", "airtable_record_id", name="uq_airtable_sync_remote"
        ),
        sa.UniqueConstraint("local_table", "local_id", name="uq_airtable_sync_local"),
    )
    op.create_table(
        "audit_logs",
        sa.Column("actor", sa.String(length=200), nullable=False),
        sa.Column("action", sa.String(length=100), nullable=False),
        sa.Column("entity_type", sa.String(length=100), nullable=False),
        sa.Column("entity_id", sa.Uuid(), nullable=True),
        sa.Column("before", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("after", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_audit_logs_action"), "audit_logs", ["action"], unique=False)
    op.create_index(op.f("ix_audit_logs_entity_id"), "audit_logs", ["entity_id"], unique=False)
    op.create_index(op.f("ix_audit_logs_entity_type"), "audit_logs", ["entity_type"], unique=False)
    op.create_table(
        "counties",
        sa.Column("slug", sa.String(length=100), nullable=False),
        sa.Column("name", sa.String(length=200), nullable=False),
        sa.Column("state", sa.String(length=2), nullable=False),
        sa.Column("fips_code", sa.String(length=5), nullable=True),
        sa.Column(
            "source_type",
            sa.Enum(
                "bulk_download", "sftp", "email", "api", "manual_upload", name="county_source_type"
            ),
            nullable=False,
        ),
        sa.Column("source_url", sa.String(length=1000), nullable=True),
        sa.Column("parsing_profile_key", sa.String(length=100), nullable=False),
        sa.Column("compliance_state_ref", sa.String(length=2), nullable=False),
        sa.Column(
            "publishing_frequency",
            sa.Enum(
                "daily",
                "weekly",
                "monthly",
                "quarterly",
                "annual",
                "irregular",
                name="publishing_frequency",
            ),
            nullable=False,
        ),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("state", "slug", name="uq_counties_state_slug"),
    )
    op.create_index(op.f("ix_counties_state"), "counties", ["state"], unique=False)
    op.create_table(
        "users",
        sa.Column("name", sa.String(length=200), nullable=False),
        sa.Column("email", sa.String(length=320), nullable=False),
        sa.Column("role", sa.Enum("admin", "manager", "agent", name="user_role"), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("email"),
    )
    op.create_table(
        "call_sheets",
        sa.Column("run_date", sa.Date(), nullable=False),
        sa.Column("assigned_user_id", sa.Uuid(), nullable=True),
        sa.Column(
            "generated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("lead_count", sa.Integer(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(["assigned_user_id"], ["users.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("run_date", "assigned_user_id", name="uq_call_sheets_date_user"),
    )
    op.create_index(
        op.f("ix_call_sheets_assigned_user_id"), "call_sheets", ["assigned_user_id"], unique=False
    )
    op.create_index(op.f("ix_call_sheets_run_date"), "call_sheets", ["run_date"], unique=False)
    op.create_table(
        "export_batches",
        sa.Column("export_type", sa.Enum("csv", "airtable", name="export_type"), nullable=False),
        sa.Column("county_id", sa.Uuid(), nullable=True),
        sa.Column("file_path", sa.String(length=1000), nullable=True),
        sa.Column("record_count", sa.Integer(), nullable=False),
        sa.Column(
            "status",
            sa.Enum("pending", "completed", "failed", name="export_status"),
            nullable=False,
        ),
        sa.Column("error_message", sa.Text(), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["county_id"], ["counties.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_export_batches_county_id"), "export_batches", ["county_id"], unique=False
    )
    op.create_index(
        op.f("ix_export_batches_export_type"), "export_batches", ["export_type"], unique=False
    )
    op.create_table(
        "ingestion_jobs",
        sa.Column("county_id", sa.Uuid(), nullable=False),
        sa.Column("source_file_path", sa.String(length=1000), nullable=False),
        sa.Column("source_file_hash", sa.String(length=64), nullable=False),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("completed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "status",
            sa.Enum("pending", "running", "completed", "failed", name="ingestion_job_status"),
            nullable=False,
        ),
        sa.Column("rows_extracted", sa.Integer(), nullable=False),
        sa.Column("rows_failed", sa.Integer(), nullable=False),
        sa.Column("error_message", sa.Text(), nullable=True),
        sa.Column("triggered_by", sa.String(length=100), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["county_id"], ["counties.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_ingestion_jobs_county_id"), "ingestion_jobs", ["county_id"], unique=False
    )
    op.create_index(
        op.f("ix_ingestion_jobs_source_file_hash"),
        "ingestion_jobs",
        ["source_file_hash"],
        unique=False,
    )
    op.create_table(
        "parsing_profile_versions",
        sa.Column("county_id", sa.Uuid(), nullable=False),
        sa.Column("version_hash", sa.String(length=64), nullable=False),
        sa.Column("profile_json", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["county_id"], ["counties.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "county_id", "version_hash", name="uq_parsing_profile_versions_county_hash"
        ),
    )
    op.create_index(
        op.f("ix_parsing_profile_versions_county_id"),
        "parsing_profile_versions",
        ["county_id"],
        unique=False,
    )
    op.create_table(
        "raw_surplus_rows",
        sa.Column("ingestion_job_id", sa.Uuid(), nullable=False),
        sa.Column("county_id", sa.Uuid(), nullable=False),
        sa.Column("raw_data", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("row_hash", sa.String(length=64), nullable=False),
        sa.Column("page_number", sa.Integer(), nullable=True),
        sa.Column(
            "extraction_method",
            sa.Enum("table", "text", "ocr", "llm_assist", name="extraction_method"),
            nullable=False,
        ),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["county_id"], ["counties.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["ingestion_job_id"], ["ingestion_jobs.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_raw_surplus_rows_county_id"), "raw_surplus_rows", ["county_id"], unique=False
    )
    op.create_index(
        op.f("ix_raw_surplus_rows_ingestion_job_id"),
        "raw_surplus_rows",
        ["ingestion_job_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_raw_surplus_rows_row_hash"), "raw_surplus_rows", ["row_hash"], unique=False
    )
    op.create_table(
        "surplus_cases",
        sa.Column("county_id", sa.Uuid(), nullable=False),
        sa.Column("raw_row_id", sa.Uuid(), nullable=True),
        sa.Column("case_number", sa.String(length=200), nullable=False),
        sa.Column("parcel_id", sa.String(length=200), nullable=True),
        sa.Column("property_address_raw", sa.Text(), nullable=True),
        sa.Column(
            "property_address_normalized", postgresql.JSONB(astext_type=sa.Text()), nullable=True
        ),
        sa.Column("sale_date", sa.Date(), nullable=True),
        sa.Column("judgment_amount", sa.Numeric(precision=14, scale=2), nullable=True),
        sa.Column("sale_amount", sa.Numeric(precision=14, scale=2), nullable=True),
        sa.Column("surplus_amount", sa.Numeric(precision=14, scale=2), nullable=False),
        sa.Column("distribution_deadline", sa.Date(), nullable=True),
        sa.Column(
            "status",
            sa.Enum(
                "new",
                "normalized",
                "classified",
                "compliance_checked",
                "researched",
                "qualified",
                "rejected",
                name="surplus_case_status",
            ),
            nullable=False,
        ),
        sa.Column("dedupe_hash", sa.String(length=64), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["county_id"], ["counties.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["raw_row_id"], ["raw_surplus_rows.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("county_id", "dedupe_hash", name="uq_surplus_cases_county_dedupe_hash"),
    )
    op.create_index(
        op.f("ix_surplus_cases_case_number"), "surplus_cases", ["case_number"], unique=False
    )
    op.create_index(
        op.f("ix_surplus_cases_county_id"), "surplus_cases", ["county_id"], unique=False
    )
    op.create_index(
        op.f("ix_surplus_cases_parcel_id"), "surplus_cases", ["parcel_id"], unique=False
    )
    op.create_index(
        op.f("ix_surplus_cases_raw_row_id"), "surplus_cases", ["raw_row_id"], unique=False
    )
    op.create_index(
        op.f("ix_surplus_cases_sale_date"), "surplus_cases", ["sale_date"], unique=False
    )
    op.create_index(op.f("ix_surplus_cases_status"), "surplus_cases", ["status"], unique=False)
    op.create_table(
        "compliance_evaluations",
        sa.Column("surplus_case_id", sa.Uuid(), nullable=False),
        sa.Column("state_rule_version", sa.String(length=64), nullable=False),
        sa.Column("is_eligible", sa.Boolean(), nullable=False),
        sa.Column("fee_cap_pct", sa.Float(), nullable=True),
        sa.Column("earliest_contact_date", sa.Date(), nullable=True),
        sa.Column("disclosures_required", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("evaluation_notes", sa.Text(), nullable=True),
        sa.Column(
            "evaluated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(["surplus_case_id"], ["surplus_cases.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_compliance_evaluations_is_eligible"),
        "compliance_evaluations",
        ["is_eligible"],
        unique=False,
    )
    op.create_index(
        op.f("ix_compliance_evaluations_surplus_case_id"),
        "compliance_evaluations",
        ["surplus_case_id"],
        unique=False,
    )
    op.create_table(
        "owners",
        sa.Column("surplus_case_id", sa.Uuid(), nullable=False),
        sa.Column("raw_name", sa.Text(), nullable=False),
        sa.Column(
            "owner_type",
            sa.Enum(
                "individual",
                "company",
                "trust",
                "estate",
                "government",
                "unknown",
                name="owner_type",
            ),
            nullable=False,
        ),
        sa.Column("first_name", sa.String(length=200), nullable=True),
        sa.Column("middle_name", sa.String(length=200), nullable=True),
        sa.Column("last_name", sa.String(length=200), nullable=True),
        sa.Column("suffix", sa.String(length=20), nullable=True),
        sa.Column("entity_name", sa.String(length=500), nullable=True),
        sa.Column("classification_confidence", sa.Float(), nullable=True),
        sa.Column(
            "classification_method",
            sa.Enum("rule", "ml", "manual", name="classification_method"),
            nullable=True,
        ),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["surplus_case_id"], ["surplus_cases.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_owners_owner_type"), "owners", ["owner_type"], unique=False)
    op.create_index(op.f("ix_owners_surplus_case_id"), "owners", ["surplus_case_id"], unique=False)
    op.create_table(
        "properties",
        sa.Column("surplus_case_id", sa.Uuid(), nullable=False),
        sa.Column("parcel_id", sa.String(length=200), nullable=True),
        sa.Column("assessed_value", sa.Numeric(precision=14, scale=2), nullable=True),
        sa.Column("legal_description", sa.Text(), nullable=True),
        sa.Column("property_type", sa.String(length=100), nullable=True),
        sa.Column("last_researched_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["surplus_case_id"], ["surplus_cases.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_properties_parcel_id"), "properties", ["parcel_id"], unique=False)
    op.create_index(
        op.f("ix_properties_surplus_case_id"), "properties", ["surplus_case_id"], unique=False
    )
    op.create_table(
        "research_results",
        sa.Column("surplus_case_id", sa.Uuid(), nullable=False),
        sa.Column("provider", sa.String(length=100), nullable=False),
        sa.Column("request_payload", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("response_payload", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column(
            "status",
            sa.Enum("success", "not_found", "error", name="research_status"),
            nullable=False,
        ),
        sa.Column(
            "fetched_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(["surplus_case_id"], ["surplus_cases.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_research_results_provider"), "research_results", ["provider"], unique=False
    )
    op.create_index(
        op.f("ix_research_results_surplus_case_id"),
        "research_results",
        ["surplus_case_id"],
        unique=False,
    )
    op.create_table(
        "leads",
        sa.Column("surplus_case_id", sa.Uuid(), nullable=False),
        sa.Column("owner_id", sa.Uuid(), nullable=True),
        sa.Column(
            "status",
            sa.Enum(
                "new",
                "qualified",
                "contacted",
                "interested",
                "contract_sent",
                "contract_signed",
                "claim_filed",
                "paid",
                "dead",
                name="lead_status",
            ),
            nullable=False,
        ),
        sa.Column("score", sa.Float(), nullable=True),
        sa.Column("score_breakdown", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("assigned_user_id", sa.Uuid(), nullable=True),
        sa.Column("airtable_record_id", sa.String(length=50), nullable=True),
        sa.Column("qualified_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["assigned_user_id"], ["users.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["owner_id"], ["owners.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["surplus_case_id"], ["surplus_cases.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("surplus_case_id"),
    )
    op.create_index(
        op.f("ix_leads_airtable_record_id"), "leads", ["airtable_record_id"], unique=False
    )
    op.create_index(op.f("ix_leads_assigned_user_id"), "leads", ["assigned_user_id"], unique=False)
    op.create_index(op.f("ix_leads_owner_id"), "leads", ["owner_id"], unique=False)
    op.create_index(op.f("ix_leads_score"), "leads", ["score"], unique=False)
    op.create_index(op.f("ix_leads_status"), "leads", ["status"], unique=False)
    op.create_table(
        "call_sheet_items",
        sa.Column("call_sheet_id", sa.Uuid(), nullable=False),
        sa.Column("lead_id", sa.Uuid(), nullable=False),
        sa.Column("priority_rank", sa.Integer(), nullable=False),
        sa.Column("called", sa.Boolean(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(["call_sheet_id"], ["call_sheets.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["lead_id"], ["leads.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("call_sheet_id", "lead_id", name="uq_call_sheet_items_sheet_lead"),
    )
    op.create_index(
        op.f("ix_call_sheet_items_call_sheet_id"),
        "call_sheet_items",
        ["call_sheet_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_call_sheet_items_lead_id"), "call_sheet_items", ["lead_id"], unique=False
    )
    op.create_table(
        "contacts",
        sa.Column("lead_id", sa.Uuid(), nullable=False),
        sa.Column(
            "contact_type",
            sa.Enum("phone", "email", "mailing_address", name="contact_type"),
            nullable=False,
        ),
        sa.Column("value", sa.Text(), nullable=False),
        sa.Column("source", sa.String(length=100), nullable=True),
        sa.Column("confidence", sa.Float(), nullable=True),
        sa.Column("is_verified", sa.Boolean(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["lead_id"], ["leads.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_contacts_contact_type"), "contacts", ["contact_type"], unique=False)
    op.create_index(op.f("ix_contacts_lead_id"), "contacts", ["lead_id"], unique=False)
    op.create_table(
        "deals",
        sa.Column("lead_id", sa.Uuid(), nullable=False),
        sa.Column(
            "stage",
            sa.Enum(
                "contract_sent", "contract_signed", "claim_filed", "paid", "lost", name="deal_stage"
            ),
            nullable=False,
        ),
        sa.Column("contract_fee_pct", sa.Float(), nullable=True),
        sa.Column("claim_amount", sa.Numeric(precision=14, scale=2), nullable=True),
        sa.Column("fee_amount", sa.Numeric(precision=14, scale=2), nullable=True),
        sa.Column("closed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["lead_id"], ["leads.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("lead_id"),
    )
    op.create_index(op.f("ix_deals_stage"), "deals", ["stage"], unique=False)
    op.create_table(
        "interactions",
        sa.Column("lead_id", sa.Uuid(), nullable=False),
        sa.Column("user_id", sa.Uuid(), nullable=True),
        sa.Column(
            "interaction_type",
            sa.Enum("call", "email", "sms", "mail", "note", name="interaction_type"),
            nullable=False,
        ),
        sa.Column("outcome", sa.String(length=100), nullable=True),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.Column(
            "occurred_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["lead_id"], ["leads.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_interactions_interaction_type"), "interactions", ["interaction_type"], unique=False
    )
    op.create_index(op.f("ix_interactions_lead_id"), "interactions", ["lead_id"], unique=False)
    op.create_index(
        op.f("ix_interactions_occurred_at"), "interactions", ["occurred_at"], unique=False
    )
    op.create_index(op.f("ix_interactions_user_id"), "interactions", ["user_id"], unique=False)
    op.create_table(
        "lead_scores",
        sa.Column("lead_id", sa.Uuid(), nullable=False),
        sa.Column("score_version", sa.String(length=50), nullable=False),
        sa.Column("total_score", sa.Float(), nullable=False),
        sa.Column("factor_breakdown", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column(
            "scored_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False
        ),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(["lead_id"], ["leads.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_lead_scores_lead_id"), "lead_scores", ["lead_id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_lead_scores_lead_id"), table_name="lead_scores")
    op.drop_table("lead_scores")
    op.drop_index(op.f("ix_interactions_user_id"), table_name="interactions")
    op.drop_index(op.f("ix_interactions_occurred_at"), table_name="interactions")
    op.drop_index(op.f("ix_interactions_lead_id"), table_name="interactions")
    op.drop_index(op.f("ix_interactions_interaction_type"), table_name="interactions")
    op.drop_table("interactions")
    op.drop_index(op.f("ix_deals_stage"), table_name="deals")
    op.drop_table("deals")
    op.drop_index(op.f("ix_contacts_lead_id"), table_name="contacts")
    op.drop_index(op.f("ix_contacts_contact_type"), table_name="contacts")
    op.drop_table("contacts")
    op.drop_index(op.f("ix_call_sheet_items_lead_id"), table_name="call_sheet_items")
    op.drop_index(op.f("ix_call_sheet_items_call_sheet_id"), table_name="call_sheet_items")
    op.drop_table("call_sheet_items")
    op.drop_index(op.f("ix_leads_status"), table_name="leads")
    op.drop_index(op.f("ix_leads_score"), table_name="leads")
    op.drop_index(op.f("ix_leads_owner_id"), table_name="leads")
    op.drop_index(op.f("ix_leads_assigned_user_id"), table_name="leads")
    op.drop_index(op.f("ix_leads_airtable_record_id"), table_name="leads")
    op.drop_table("leads")
    op.drop_index(op.f("ix_research_results_surplus_case_id"), table_name="research_results")
    op.drop_index(op.f("ix_research_results_provider"), table_name="research_results")
    op.drop_table("research_results")
    op.drop_index(op.f("ix_properties_surplus_case_id"), table_name="properties")
    op.drop_index(op.f("ix_properties_parcel_id"), table_name="properties")
    op.drop_table("properties")
    op.drop_index(op.f("ix_owners_surplus_case_id"), table_name="owners")
    op.drop_index(op.f("ix_owners_owner_type"), table_name="owners")
    op.drop_table("owners")
    op.drop_index(
        op.f("ix_compliance_evaluations_surplus_case_id"), table_name="compliance_evaluations"
    )
    op.drop_index(
        op.f("ix_compliance_evaluations_is_eligible"), table_name="compliance_evaluations"
    )
    op.drop_table("compliance_evaluations")
    op.drop_index(op.f("ix_surplus_cases_status"), table_name="surplus_cases")
    op.drop_index(op.f("ix_surplus_cases_sale_date"), table_name="surplus_cases")
    op.drop_index(op.f("ix_surplus_cases_raw_row_id"), table_name="surplus_cases")
    op.drop_index(op.f("ix_surplus_cases_parcel_id"), table_name="surplus_cases")
    op.drop_index(op.f("ix_surplus_cases_county_id"), table_name="surplus_cases")
    op.drop_index(op.f("ix_surplus_cases_case_number"), table_name="surplus_cases")
    op.drop_table("surplus_cases")
    op.drop_index(op.f("ix_raw_surplus_rows_row_hash"), table_name="raw_surplus_rows")
    op.drop_index(op.f("ix_raw_surplus_rows_ingestion_job_id"), table_name="raw_surplus_rows")
    op.drop_index(op.f("ix_raw_surplus_rows_county_id"), table_name="raw_surplus_rows")
    op.drop_table("raw_surplus_rows")
    op.drop_index(
        op.f("ix_parsing_profile_versions_county_id"), table_name="parsing_profile_versions"
    )
    op.drop_table("parsing_profile_versions")
    op.drop_index(op.f("ix_ingestion_jobs_source_file_hash"), table_name="ingestion_jobs")
    op.drop_index(op.f("ix_ingestion_jobs_county_id"), table_name="ingestion_jobs")
    op.drop_table("ingestion_jobs")
    op.drop_index(op.f("ix_export_batches_export_type"), table_name="export_batches")
    op.drop_index(op.f("ix_export_batches_county_id"), table_name="export_batches")
    op.drop_table("export_batches")
    op.drop_index(op.f("ix_call_sheets_run_date"), table_name="call_sheets")
    op.drop_index(op.f("ix_call_sheets_assigned_user_id"), table_name="call_sheets")
    op.drop_table("call_sheets")
    op.drop_table("users")
    op.drop_index(op.f("ix_counties_state"), table_name="counties")
    op.drop_table("counties")
    op.drop_index(op.f("ix_audit_logs_entity_type"), table_name="audit_logs")
    op.drop_index(op.f("ix_audit_logs_entity_id"), table_name="audit_logs")
    op.drop_index(op.f("ix_audit_logs_action"), table_name="audit_logs")
    op.drop_table("audit_logs")
    op.drop_table("airtable_sync_records")
    # ### end Alembic commands ###
    bind = op.get_bind()
    for enum_name in _ENUM_TYPE_NAMES:
        sa.Enum(name=enum_name).drop(bind, checkfirst=True)
