"""parse review queue

Revision ID: b4dcfa4ed5eb
Revises: 7115f38f3379
Create Date: 2026-08-02 22:04:34.280065

"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = "b4dcfa4ed5eb"
down_revision: str | None = "7115f38f3379"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None

# extraction_method and surplus_source_type were created by earlier migrations. Reusing a
# type inside create_table would try to CREATE TYPE again, so they are referenced with
# create_type=False. Only the two types this migration introduces are dropped on downgrade.
_EXISTING_EXTRACTION_METHOD = postgresql.ENUM(
    "table", "text", "ocr", "llm_assist", name="extraction_method", create_type=False
)
_EXISTING_SURPLUS_SOURCE = postgresql.ENUM(
    "explicit",
    "county_config",
    "derived",
    "ambiguous",
    "absent",
    name="surplus_source_type",
    create_type=False,
)

_NEW_ENUM_TYPE_NAMES: tuple[str, ...] = ("routing_decision_type", "review_status")


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "parse_review_items",
        sa.Column("parsed_document_id", sa.Uuid(), nullable=False),
        sa.Column("raw_surplus_row_id", sa.Uuid(), nullable=True),
        sa.Column("county_id", sa.Uuid(), nullable=True),
        sa.Column("table_index", sa.Integer(), nullable=False),
        sa.Column("page_number", sa.Integer(), nullable=False),
        sa.Column("row_index_on_page", sa.Integer(), nullable=False),
        sa.Column("raw_values", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("canonical_values", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column(
            "routing",
            sa.Enum("auto_accept", "review", "quarantine", name="routing_decision_type"),
            nullable=False,
        ),
        sa.Column("reason", sa.Text(), nullable=False),
        sa.Column("confidence", sa.Float(), nullable=False),
        sa.Column("extraction_method", _EXISTING_EXTRACTION_METHOD, nullable=False),
        sa.Column("surplus_amount", sa.Numeric(precision=14, scale=2), nullable=True),
        sa.Column("surplus_source", _EXISTING_SURPLUS_SOURCE, nullable=False),
        sa.Column(
            "status",
            sa.Enum("pending", "resolved", "rejected", name="review_status"),
            nullable=False,
        ),
        sa.Column("resolved_by", sa.String(length=200), nullable=True),
        sa.Column("resolved_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("resolution_notes", sa.Text(), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["county_id"], ["counties.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(
            ["parsed_document_id"], ["parsed_documents.id"], ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(
            ["raw_surplus_row_id"], ["raw_surplus_rows.id"], ondelete="SET NULL"
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "parsed_document_id",
            "table_index",
            "page_number",
            "row_index_on_page",
            name="uq_parse_review_items_row",
        ),
    )
    op.create_index(
        op.f("ix_parse_review_items_county_id"), "parse_review_items", ["county_id"], unique=False
    )
    op.create_index(
        op.f("ix_parse_review_items_parsed_document_id"),
        "parse_review_items",
        ["parsed_document_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_parse_review_items_raw_surplus_row_id"),
        "parse_review_items",
        ["raw_surplus_row_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_parse_review_items_routing"), "parse_review_items", ["routing"], unique=False
    )
    op.create_index(
        op.f("ix_parse_review_items_status"), "parse_review_items", ["status"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_parse_review_items_status"), table_name="parse_review_items")
    op.drop_index(op.f("ix_parse_review_items_routing"), table_name="parse_review_items")
    op.drop_index(op.f("ix_parse_review_items_raw_surplus_row_id"), table_name="parse_review_items")
    op.drop_index(op.f("ix_parse_review_items_parsed_document_id"), table_name="parse_review_items")
    op.drop_index(op.f("ix_parse_review_items_county_id"), table_name="parse_review_items")
    op.drop_table("parse_review_items")
    # ### end Alembic commands ###
    bind = op.get_bind()
    for enum_name in _NEW_ENUM_TYPE_NAMES:
        sa.Enum(name=enum_name).drop(bind, checkfirst=True)
